### ISSUE TITLE
Authentication + Clean up

### ISSUE THREAD

**Issue by Warrenwwang1** [codebase-berkeley/tgif-voting-portal#24]
Login page backend (auth)
Clean up code

**Comment by ryanhzhao** [comment]
Resources for Authentication
- Passport.js http://www.passportjs.org/
- Google guides about configuring "passport.js + express" (I wasn't able to find any single guide with everything, so you might have to look at many resources). This is a decent one https://dev.to/phyllis_yym/beginner-s-guide-to-google-oauth-with-passport-js-2gh4

**Comment by ryanhzhao** [comment]
Here is my passport code if you guys want something to get you all started. https://github.com/KnightAsterial/mentored-passportjs-sp21/tree/master

**Comment by ryanhzhao** [comment]
Potential structure/flow for authentication
1. have user hit login endpoint and get redirected to google oauth
2. after successful login through Google/CalNet, check with our database to see if the user is on our whitelist. If yes, redirect them to the dashboard. if not, redirect them to a "sorry, you're not on our list. check with the TGIF admins"
3. make a getUser or isAdmin endpoint and have the React client ping the endpoint to see if they are an admin or not (using the identity established through passport). Use the results for React's conditional rendering.
4. secure every endpoint on the Express-side to make sure that the user is authenticated (on our whitelist) and add extra checks for admin-only endpoints to verify they are an admin
