### ISSUE TITLE
Reflect Dashboard Vote in details

### ISSUE THREAD

**Issue by Warrenwwang1** [codebase-berkeley/tgif-voting-portal#27]
1. Voting button highlight isn't reflected on the details when you vote on the dashboard
2. 
recreation
- vote on the dashboard
- go to the view discussion, the buttons will not be highlighted even though your vote was recorded

**Comment by wistyanh** [comment]
idt this includes changing the voting buttons on the front end so this should be done! will be included in our master anh-jorge-final-tasks branch:)
