### ISSUE TITLE
Proposal Details Bugs 

### ISSUE THREAD

**Issue by Warrenwwang1** [codebase-berkeley/tgif-voting-portal#39]
### Vote progress bar
issue with the vote progress bars, basically it doesn’t show the vote no in %voted / % unvoted
<img width="565" alt="Screen Shot 2021-04-25 at 3 10 35 PM" src="https://user-images.githubusercontent.com/30469905/116011147-64f18180-a5d8-11eb-937a-abb320542574.png">

### fix long content being covered by progress bar / vote
If the content of the details is too long (long title), the 
voting buttons or progress bars cover the content (depending on what is conditionally rendered based on their privileges)
- potential fix is to add the progress bars into the flex div that holds the other content (title, desc, link, amt etc) so that it just renders below the rest of the content

![image](https://user-images.githubusercontent.com/30469905/116010696-6f5e4c00-a5d5-11eb-9470-079db1abe4d2.png)
<img width="508" alt="Screen Shot 2021-04-25 at 2 50 03 PM" src="https://user-images.githubusercontent.com/30469905/116010705-8604a300-a5d5-11eb-95b0-f9301bb7b169.png">

**Comment by wistyanh** [comment]
i think this is done?? just the last part regarding the margins/i guess placement when you make the screen really small looks weird but I'm not sure how to fix?
